#!/bin/bash -efu

usage() {
    echo "usage: $OCDEV_PROGNAME <command>"
    echo
    echo "Available commands:"
    echo "  build-image  Build Docker images"
    echo "  up           "
}

ocdevcluster-build-image() {
    ocdev openshift build-image
    ocdev pod build-image
    ocdev registry build-image
}

ocdevcluster-up() {
    ocdev openshift up
    sleep 2  # FIXME(dmage)
    ocdev openshift create-defaults
}

ocdevcluster-down() {
    ocdev openshift down
}

ocdevutil-main "ocdevclusterhelper-" "ocdevcluster-" "$@"
